[src]
include = ["compat"]

[environment]
python = ".venv-compat"

[terminal]
error-on-warning = true

[rules]
possibly-unresolved-reference = "error"
possibly-missing-import = "error"
blanket-ignore-comment = "error"
division-by-zero = "error"
unsound-yield = "error"
unsupported-dynamic-base = "error"
missing-override-decorator = "error"
